baseURL = 'https://htby.github.io/weblog/'
languageCode = 'ja'
title = "htby's garden"
theme = 'hugo-til'
copyright = 'Yasuhiro Hatabe'

[author]
  name = '畑邊康浩'

[services]
  [services.googleAnalytics]
    ID = "G-5NH117CD2L"

[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 30
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 40

[outputs]
  home = ['html']
  section = ['html', 'rss', 'json']
  page = ['html']
  
[params]
  # Set how dates should appear across the site.
  # For format options, visit https://gohugo.io/functions/time/format/
  # Default: :date_long
  dateFormat = ':date_long'

  # Show content graph for single notes and posts.
  # Default: true
  showGraph = true
  
  # Author details for the JSON-LD structured data.
  [params.author]
    name = 'Yasuhiro Hatabe'

  # Homepage setup
  [params.home]
    # Display recent blog posts on the homepage.
    # Default: true
    showRecentPosts = true

    # Set how many recent blog posts to show.
    # Default: 3
    recentPostsLimit = 5

    # Display recent notes on the homepage.
    # Default: true
    showRecentNotes = true

    # Set how many recent notes to show.
    # Default: 5
    recentNotesLimit = 5

  # Notes page setup
  [params.notes]
    # Set the number of notes to list on each page.
    # Default: 20
    pageSize = 20

    # Show a filter option for note categories above the notes list.
    # Default: true
    showCategoryFilter = true

  # Footer setup
  [params.footer]
    # Specify the Creative Commons license to apply to your content.
    # Options: `by`, `by_sa`, `by_nc`, `by_nc_sa`, `by_nd`, `by_nc_nd`, `zero`, `none`
    # Learn more at https://creativecommons.org/share-your-work/cclicenses/
    # Default: none
    creativeCommonsLicense = 'none'

    # Show a credit link to the Today I Learned theme in the footer.
    # Default: true
    showThemeCredit = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true